config/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from app.views import ExploreView

admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    url(r'^$',          'app.views.home', name='home'),
    url(r'^writer$',    'app.views.writer', name='writer'),
    url(r'^explore$',   ExploreView.as_view(), name='explore'),
    url(r'^admin/',     include(admin.site.urls)),
    url(r'^api/',       include('liang.modules.api.urls')),
    url(r'^p/',         include('liang.modules.articles.urls', namespace='articles')),
    url(r'^comments/',  include('liang.modules.comments.urls')),
    url(r'^accounts/',  include('liang.modules.accounts.urls')),
    url(r'^people/',    include('liang.modules.peoples.urls', namespace="people")),
    url(r'^auth/',      include('django.contrib.auth.urls')),
)

liang/modules/articles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^create$', views.ArticleCreate.as_view(), name='article_create'),
    # url(r'^(?P<book_id>\d+)/create$', views.ArticleCreate.as_view(), name='article_create_in_book'),
    # url(r'^(?P<pk>\d+)/update$', views.ArticleUpdate.as_view(), name='article_update'),
    # url(r'^book/create$', views.BookCreate.as_view(), name='book_create'),
    # url(r'^book$', views.BookList.as_view(), name='book_list'),

    url(r'^(?P<pk>\d+)$', views.ArticleView.as_view(), name='article_detail'),
    url(r'^book/(?P<pk>\d+)$', views.BookView.as_view(), name='book_detail'),
    url(r'^api/(?P<action>\S+)$', views.WriterApiView.as_view(), name='api_list'),

)

liang/modules/peoples/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns(
    '',
    # Examples:
    url(r'^(?P<pk>\d+)$', views.PeopleDetail.as_view(), name='detail'),
)

liang/base/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import Manager
from liang.base.kits import jsonify


class BaseManager(models.Manager):
    def all(self):
        return self.filter().all()

    def filter(self, *args, **kwargs):
        kwargs.update({'enable': True})
        return super(BaseManager, self).filter(*args, **kwargs)


class BaseModel(models.Model):
    enable = models.BooleanField(default=True)

    objects = BaseManager()

    def delete(self, using=None):
        self.enable = False
        self.save(using=using, update_fields=['enable'])
        return True

    @property
    def dict(self):
        if hasattr(self, 'to_dict'):
            d = self.to_dict()
        else:
            d = self.__dict__
        return d

    def to_json(self):
        return jsonify(self.dict)

    class Meta:
        abstract = True

liang/modules/articles/models.py
# -*- coding: utf-8 -*-
from BeautifulSoup import BeautifulSoup
from django.conf import settings
from django.contrib.humanize.templatetags import humanize
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from liang.base.decorator import time_spend
from liang.base.models import BaseModel

DRAFT = 0
HIDDEN = 1
PUBLISHED = 2


class AbstractBook(BaseModel):
    name = models.CharField(max_length=64, verbose_name=u'书籍名称')
    rate = models.FloatField(default=5, verbose_name=u'评分')
    rate_users = models.ManyToManyField(to=settings.AUTH_USER_MODEL, related_name='rate_books')
    author_name = models.CharField(max_length=64, blank=True, verbose_name=u'作者名称')
    cover = models.ImageField(verbose_name=u"封面", upload_to="cover", null=True, default='cover/default_book.png')
    summary = models.CharField(max_length=300, blank=True, verbose_name="概要")
    date_created = models.DateTimeField(default=lambda *args: timezone.now())
    date_updated = models.DateTimeField(default=lambda *args: timezone.now())

    @property
    def published_articles(self):
        return self.articles.filter(status=PUBLISHED)

    def get_absolute_url(self):
        return "/p/book/%s" % (self.pk, )

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Book(AbstractBook):
    owner = models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='books')

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.date_updated = timezone.now()
        saved = super(Book, self).save(force_insert=force_insert, force_update=force_update, using=using,
                                       update_fields=update_fields)
        return saved

    @classmethod
    def search(cls, q=None, order_by='-pk', *args, **kwargs):
        if not q:
            q = ''
        return cls.objects.filter(name__contains=q).order_by(order_by)

    def to_dict(self):
        json_dict = self.__dict__
        json_dict.update({
            "owner": self.owner,
            "author_name": self.author_name if not not self.author_name else str(self.owner),
            "date_created": humanize.naturaltime(self.date_created),
            "date_updated": humanize.naturaltime(self.date_updated)
        })
        return json_dict

    def delete(self, using=None):
        self.articles.update(enable=False)
        self.enable = False
        return super(Book, self).delete(using=using)

    class Meta:
        abstract = False


class Article(BaseModel):
    STATUS_CHOICES = ((DRAFT, _(u'草稿')),
                      (HIDDEN, _(u'隐藏')),
                      (PUBLISHED, _(u'发表')))
    # 标题
    title = models.CharField(max_length=64, verbose_name=u'标题')
    book = models.ForeignKey(to="Book", null=True, related_name='articles')
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='articles')
    author_name = models.CharField(max_length=64, blank=True, verbose_name=u'作者名称')
    summary = models.TextField(blank=True, max_length=140, verbose_name=_(u'简述'))
    content = models.TextField(blank=True, max_length=100000, verbose_name=_(u'正文'))
    slug = models.SlugField(
        _('slug'), max_length=255,
        unique_for_date='date_created',
        help_text=_("Used to build the entry's URL."))
    status = models.IntegerField(
        _('状态'), db_index=True,
        choices=STATUS_CHOICES, default=DRAFT)
    start_publication = models.DateTimeField(
        _('start publication'),
        db_index=True, blank=True, null=True,
        help_text=_('Start date of publication.'))
    end_publication = models.DateTimeField(
        _('end publication'),
        db_index=True, blank=True, null=True,
        help_text=_('End date of publication.'))
    date_created = models.DateTimeField(default=lambda *args: timezone.now())
    date_updated = models.DateTimeField(default=lambda *args: timezone.now())

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.date_updated = timezone.now()
        self.summary = (''.join(BeautifulSoup(self.content).findAll(text=True)))[0: 140] + "..."
        saved = super(Article, self).save(force_insert=force_insert,
                                          force_update=force_update,
                                          using=using,
                                          update_fields=update_fields)
        self.book.date_updated = timezone.now()
        self.book.save()
        return saved

    @classmethod
    def new_instance(cls, book, user, title=None, title_index=0):
        if not title:
            title = u'新建文章'
        if title_index > 0:
            query_title = "%s %d" % (title, title_index)
        else:
            query_title = title
        exist_book = cls.objects.filter(book=book, author=user, title=query_title)
        if len(exist_book) > 0:
            title_index += 1
            return cls.new_instance(book=book,
                                    user=user,
                                    title=title,
                                    title_index=title_index)
        else:
            article = cls(book=book, author=user, title=query_title)
            article.author_name = book.author_name
            article.save()
            return article

    @property
    def is_actual(self):
        """
        Checks if an entry is within his publication period.
        """
        now = timezone.now()
        if self.start_publication and now < self.start_publication:
            return False

        if self.end_publication and now >= self.end_publication:
            return False
        return True

    @property
    def is_visible(self):
        return self.is_actual and self.status == PUBLISHED

    def get_absolute_url(self):
        return "/p/%s" % (self.pk, )

    @classmethod
    @time_spend
    def search(cls, q=None, order_by='-pk', *args, **kwargs):
        if not q:
            q = ''
        return cls.objects.filter(title__contains=q).order_by(order_by)

    @time_spend
    def to_dict(self):
        json_dict = self.__dict__
        json_dict.update({
            "book": self.book,
            "author": self.author,
            "author_name": self.author_name if not not self.author_name else str(self.author),
            "date_created": humanize.naturaltime(self.date_created),
            "date_updated": humanize.naturaltime(self.date_updated)
        })
        if json_dict.has_key('content'):
            json_dict.pop('content')
        return json_dict

    def __str__(self):
        return self.title

    class Meta:
        unique_together = (('book', 'title'),)
        ordering = ("-date_updated", )

liang/modules/articles/forms.py
# -*- coding: utf-8 -*-
from django import forms
from app.forms.angular_model import NgModelFormMixin
from liang.modules.articles.models import Book, Article


class BookForm(forms.ModelForm):
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['cover'].required = False
        self.fields['owner'].widget = forms.HiddenInput()
        self.fields['owner'].initial = request.user

    class Meta:
        model = Book
        fields = ['cover', 'author_name', 'name', 'owner', 'summary']


class ArticleForm(NgModelFormMixin, forms.ModelForm):

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields['author'].widget = forms.HiddenInput()
        self.fields['author'].initial = request.user
        self.fields['book'].queryset = Book.objects.filter(owner=request.user.id)
        if self.instance and self.instance.book:
            self.request.book = self.instance.book

        if hasattr(self.request, "book"):
            self.fields['book'].widget = forms.HiddenInput()
            self.fields['book'].initial = self.request.book

    class Meta:
        model = Article
        fields = ['book', 'title', 'content', 'author', 'status']

liang/base/views.py
# -*- coding: utf-8 -*-
import functools
from django import http
from django.views.generic import View
from liang.base.decorator import prep_params
from liang.base.kits import render_json


class ApiView(View):
    prefix = 'action'

    @prep_params(page_index=0, page_size=10)
    def dispatch(self, request, action=None, page_index=0, page_size=10, *args, **kwargs):
        action_name = "%s_%s" % (self.prefix, action)
        if hasattr(self, action_name):
            return render_json(getattr(self, action_name)(request,
                                                          page_index=int(page_index),
                                                          page_size=int(page_size), *args, **kwargs))
        else:
            return http.HttpResponseNotFound()

liang/modules/articles/views.py
# -*- coding: utf-8 -*-
import json
import bleach
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, View
from liang.base.views import ApiView
from liang.modules.articles.forms import ArticleForm, BookForm
from liang.modules.articles.models import Article, Book


class BookView(DetailView):
    model = Book


class BookCreate(CreateView):
    model = Book
    form_class = BookForm

    def get_form(self, form_class):
        """
        Returns an instance of the form to be used in this view.
        """
        kwargs = self.get_form_kwargs()
        kwargs.update({
            "request": self.request,
        })
        return form_class(**kwargs)


class BookList(ListView):
    model = Book


class ArticleView(DetailView):
    model = Article


class ArticleCreate(CreateView):
    form_class = ArticleForm
    model = Article

    def get_form(self, form_class):
        """
        Returns an instance of the form to be used in this view.
        """
        kwargs = self.get_form_kwargs()
        kwargs.update({
            "request": self.request
        })
        return form_class(**kwargs)

    def get(self, request, book_id=None, *args, **kwargs):
        if book_id:
            book = Book.objects.get(pk=book_id)
            request.book = book
        return super(ArticleCreate, self).get(request, *args, **kwargs)

    @property
    def success_url(self, *args, **kwargs):
        return "/p/%s" % self.object.pk


class ArticleUpdate(UpdateView):
    model = Article
    form_class = ArticleForm

    def get_form(self, form_class):
        """
        Returns an instance of the form to be used in this view.
        """
        kwargs = self.get_form_kwargs()
        kwargs.update({
            "request": self.request
        })
        return form_class(**kwargs)


class WriterApiView(ApiView):

    def action_article(self, request, *args, **kwargs):
        pk = request.GET.get('pk')
        article = Article.objects.get(pk=pk)
        return article.__dict__

    def action_article_get(self, request, *args, **kwargs):
        data = request.GET
        book_id = data.get('book')
        return Book.objects.get(pk=book_id).articles.all()

    def action_article_search(self, request, page_index, page_size, *args, **kwargs):
        q = request.GET.get('q')
        if not q: q = ''
        return Article.objects.filter(title__contains=q).all()[page_index: page_size]

    def action_article_create(self, request, *args, **kwargs):
        data = json.loads(request.body)
        article = Article.new_instance(book=Book.objects.get(pk=data.pop('book')), user=request.user)
        return Article.objects.get(pk=article.pk)

    def action_article_update(self, request, *args, **kwargs):
        data = json.loads(request.body)
        pk = data.get('id')
        article = get_object_or_404(Article, pk=pk)
        data.update({
            'author': request.user.id,
            'book': article.book_id,
        })
        form = ArticleForm(request=request, data=data, instance=article)
        if form.is_valid():
            article = form.save()
            return article
        return {
            'errors': form.errors,
        }

    def action_article_delete(self, request, *args, **kwargs):
        data = json.loads(request.body)
        article_id = data.get('id')
        article = Article.objects.get(pk=article_id)
        article.delete()
        return {
            "success": Article.objects.filter(pk=article_id).count() == 0
        }

    def action_book_get(self, request, *args, **kwargs):
        return request.user.books.all()

    def action_book_search(self, request, page_index, page_size, *args, **kwargs):
        q = request.GET.get('q')
        return Book.search(q=q)[page_index: page_size]

    def action_book_create(self, request, *args, **kwargs):
        data = json.loads(request.body)
        data.update({
            'owner': request.user.id
        })
        form = BookForm(request=request, data=data)
        if form.is_valid():
            book = form.save()
            return book
        return {
            "errors": form.errors
        }

    def action_book_update(self, request, *args, **kwargs):
        data = json.loads(request.body)
        pk = data.get('id')
        book = get_object_or_404(Book, pk=pk)
        data.update({
            'owner': request.user.id
        })
        form = BookForm(request=request, data=data, instance=book)
        if form.is_valid():
            book = form.save()
            return book
        return {
            "success": False
        }

    def action_book_delete(self, request, *args, **kwargs):
        data = json.loads(request.body)
        book_id = data.get('id')
        book = Book.objects.get(pk=book_id)
        book.delete()
        return {
            "success": not book.enable
        }

liang/modules/articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block app_name %}article{% endblock %}
{% block title %}
    {{ object.title }} - {{ object.book.name }}
{% endblock %}
{% block main_style %}
    <link rel="stylesheet" href="/static/application/theme/article.css">
{% endblock %}
{% block header %}{% endblock %}
{% block main %}
    <div>
        {% include 'layouts/navbar.html' %}
        <div class="container">
            <div class="row">
                <div id="article" class="col-md-8">
                    <h2>{{ object.title }}</h2>

                    <p class="article-info">
                    <span>
                        <a href="{% url "articles:book_detail" pk=object.book.pk %}">
                            《{{ object.book.name }}》
                        </a>
                    </span>
                        <span> &bullet; {{ object.author }}</span>
                        <span class="text-muted small"> &bullet; {{ object.date_created|naturaltime }}</span>
                    </p>

                    <div id="content">
                        {{ object.content|safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block main_script %}
    <script>
        window.session = window.session || {};
        window.session.article = {{ object.to_json|safe }};
    </script>
    <script src="/static/application/pages/article.js"></script>
{% endblock %}

liang/modules/articles/templates/articles/article_form.html
{% extends 'articles/base_form.html' %}

{% block content %}
    <form method="post"
          name="{{ form.form_name }}"
          id="articles_form"
          class="single-form"
          action="{{ view.request.path }}"
          enctype="multipart/form-data">
        {% if request.book %}
        <h1>{{ request.book }}</h1>
        {% endif %}
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-block btn-primary">提交</button>
    </form>
{% endblock %}

liang/modules/articles/templates/articles/article_list.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

liang/modules/articles/templates/articles/base_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" id="articles_form" class="single-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-block btn-primary">Submit</button>
    </form>
{% endblock %}

liang/modules/articles/templates/articles/book_default_list.html
{% load comments %}
<ul class="list-unstyled">
    {% for book in book_list %}
        <li>
            <div>{{ book.owner }}: <a href="{% url "articles:book_detail" pk=book.pk %}">{{ book.name }}</a></div>
            {% get_comment_count for book as comment_count %}
            <div class="text-muted small">评
                <a href="{{ book|comments_link }}">
                    <span class="text-muted small">({{ comment_count }})</span>
                </a>
            </div>
        </li>
    {% endfor %}
</ul>

liang/modules/articles/templates/articles/book_detail.html
{% extends 'base.html' %}
{% load humanize tagging comments %}
{% block app_name %}book{% endblock %}
{% block title %}
    {{ object.title }}
{% endblock %}
{% block main_style %}
    <link rel="stylesheet" href="/static/application/theme/book.css">
{% endblock %}
{% block header %}{% endblock %}
{% block main %}
    <div id="mainContainer" ng-controller="BookController">
        {% include 'layouts/navbar.html' %}
        <div class="container">
            <div class="col-md-8">
                <div id="book_description">
                    <div class="row">
                        <div class="col-xs-2 text-right"><img width="75" height="100"
                                                              src="{{ MEDIA_URL }}{{ object.cover }}">
                        </div>
                        <blockquote class="col-xs-10">
                            <h1>{{ object.name }}</h1>
                            {% csrf_token %}
                            <p>
                            <span>作者:
                                <a href="{% url "people:detail" pk=object.owner.id %}">
                                    {{ object.author_name }}
                                </a>
                            </span>
                            </p>

                            <div class="text-muted small">
                                <rating class='ng-rate'
                                        ng-model="book.rate"
                                        max="5"
                                        readonly="isReadonly"
                                        on-hover="hoveringOver(value)"
                                        on-leave="overStar = null">
                                </rating>
                                {% verbatim %}
                                <span>{{ book.rate }} 分</span>
                                {% endverbatim %}
                            </div>
                            <div class="text-muted small">
                                <span>创建时间: {{ object.date_created|naturaltime }}</span>
                            </div>
                        </blockquote>
                    </div>
                </div>
                <div id="articles">
                    <ul class="list-unstyled">
                        {% for article in object.articles.all %}
                            <li class="article-item">
                                <div>
                                <span>
                                    <a href="{% url 'articles:article_detail' pk=article.pk %}" class="title">
                                        {{ article.title }}
                                    </a>
                                </span>
                                </div>
                                <div class="text-muted small">
                                    <span>{{ article.date_updated|naturaltime }}</span>
                                </div>
                                {% if article.summary %}
                                    <div class="small">{{ article.summary }}</div>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block main_script %}
    <script>
        window.session.book = {{ object.to_json|safe }};
    </script>
    <script src="/static/application/pages/book.js"></script>
{% endblock %}

liang/modules/articles/templates/articles/book_form.html
{% extends 'articles/base_form.html' %}
{% load tagging %}

{% block content %}
    <form method="post" id="articles_form"
          class="single-form"
          action="{{ view.request.path }}"
          enctype="multipart/form-data">
        {% csrf_token %}
        <ul class="list-unstyled">
            {{ form }}
        </ul>
        <button type="submit" class="btn btn-block btn-primary">提交</button>
    </form>
{% endblock %}
{#{% block basic_source %}#}
{#{% endblock %}#}

liang/modules/articles/templates/articles/book_list.html
{% extends 'base.html' %}
{% block content %}
    {% with book_list as book_list %}
        {% include 'articles/book_default_list.html' %}
    {% endwith %}
{% endblock %}

liang/modules/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
    <form method="post" id="article_new" >
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-block btn-primary">Submit</button>
    </form>
{% endblock %}